workflows:
  android-build:
    name: Build Android APK
    environment:
      android:
        api_level: 30
        build_tools_version: "30.0.3"
    scripts:
      - echo "Derleme başlıyor..."
      - ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
