workflows:
  android-workflow:
    name: Build Android App
    environment:
      android:
        api_level: 30
        build_tools_version: "30.0.3"
      java:
        version: 11
    scripts:
      - echo "Derleme başlıyor..."
      - ./gradlew clean assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - senin.emailin@example.com
