version: '3.8'

services:
  web:
    container_name: 'sosmed-web-backend'
    build: .
    env_file:
      - app.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run main.go -b 0.0.0.0
    links:
      - db
  db:
    container_name: 'sosmed-postgres'
    image: postgres:alpine
    env_file:
      - app.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5555:5555"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  migrate:
    container_name: 'sosmed-migrate'
    image: migrate/migrate
    env_file:
      - app.env
    volumes:
      - .:/migration
    command: "migrate -source file://migration -database ${POSTGRES_URI} up"
    links:
      - db

volumes:
  postgres-db: